FROM mcr.microsoft.com/dotnet/sdk:6.0 AS base
WORKDIR /app

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM base AS final

WORKDIR /app

ENTRYPOINT ["dotnet", "logger.dll"]
